name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like?
      placeholder: A clear and concise description of the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this?
      placeholder: Describe the problem this feature would solve or the workflow it would improve
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you implement it?
      placeholder: If you have ideas about how this feature could be implemented, please share them here
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about
      placeholder: Describe any alternative solutions or features you've considered
    validations:
      required: false
